### PR TITLE
Use pre-commit hooks to automatically run various pre-commit hooks.

### PR DESCRIPTION
**Pull request by taegyunkim**
When someone tries to commit code, pre-commit hooks will be run for changed files, and updates those files. Like following: 

```
$ pre-commit install
pre-commit installed at /home/asottile/workspace/pytest/.git/hooks/pre-commit
$ git commit -m "Add super awesome feature"
black....................................................................Passed
blacken-docs.........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Flake8...................................................................Passed
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rst..................................................(no files to check)Skipped
changelog filenames..................................(no files to check)Skipped
[master 146c6c2c] Add super awesome feature
 1 file changed, 1 insertion(+)
```

### CODE REVIEW

**Comment by anirudhSK** [comment]
When are these pre-commit hooks automatically run?

**Comment by taegyunkim** [comment]
> When are these pre-commit hooks automatically run?

See my previous comment.

**Comment by anirudhSK** [comment]
OK. That's simple enough. Can we run manually run pre-commit on the current state of the code base and add the resulting changes as a commit to this pull request? I can then merge it.

**Comment by taegyunkim** [comment]
> OK. That's simple enough. Can we run manually run pre-commit on the current state of the code base and add the resulting changes as a commit to this pull request? I can then merge it.

Done

**Review by XiangyuG — APPROVED** [review]

**Pull request merged**
