### PR TITLE
Add initialization for stateful vars

### PR DESCRIPTION
**Pull request by XiangyuG**
Change the template to initialize the stateful vars

### CODE REVIEW

**Comment by taegyunkim** [comment]
Why is this necessary?

**Comment by XiangyuG** [comment]
> Why is this necessary?

> Because otherwise it will give a random value for initialization which is not a good way. Just for guarantee, we provide the initial value set it be 0.

**Comment by taegyunkim** [comment]
Isn't the default value 0 for ints? 

```C
struct Point {
  int x;
}

harness void main() {
  |Point| p1;
  assert(p1.x == 0);
}
```

succeeds where

```C
struct Point {
  int x;
}

harness void main() {
  |Point| p1;
  assert(p1.x == 1);
}
```

this doesn't

**Comment by anirudhSK** [comment]
@taegyunkim: It's better not to rely on the fields being initialized to 0, because 0 initialization for ints isn't documented anywhere in the manual.

**Comment by taegyunkim** [comment]
@anirudhSK right, I also checked the manual, and it only hinted but not stated this.

**Review by taegyunkim — APPROVED** [review]

**Pull request merged**
