### PR TITLE
Use sketch intermediate representation to generate z3 formula for counterexample generation. 

### LINKED ISSUE #161: Bug in SKETCH's generation of smt2 file.
As @taegyunkim pointed out here: https://lists.csail.mit.edu/pipermail/sketchusers/2019-July/000092.html, there's a bug in the way the smt2 file is generated.

This is causing several unit tests to fail during CI, e.g., https://github.com/chipmunk-project/chipmunk/pull/160 and https://github.com/chipmunk-project/chipmunk/pull/157.

### PR DESCRIPTION
**Pull request by taegyunkim**
Fixes #161

### CODE REVIEW

**Comment by anirudhSK** [comment]
We could try using debug-fake-solver to prevent the backend from running now that we don't need the writeSMT flag (https://lists.csail.mit.edu/pipermail/sketchusers/2019-April/000082.html).

**Comment by taegyunkim** [comment]
All tests in tests/test_iterative_solver.py pass on cyclops. not sure why it's failing on appveyor

**Comment by anirudhSK** [comment]
The error message on AppVeyor says that the dag file was not found. It might be worth using Remote Desktop to get into the AppVeyor machine to see what’s going on: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by taegyunkim** [comment]
> The error message on AppVeyor says that the dag file was not found. It might be worth using Remote Desktop to get into the AppVeyor machine to see what’s going on: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

Figured it out, and fixed. --debug-fake-solver was the reason.

**Review by anirudhSK — APPROVED** [review]

**Pull request merged**
