### PR TITLE
Generate parser/lexer using antlr for `pip install -e` invocation

### PR DESCRIPTION
**Pull request by taegyunkim**
Addresses #83. 

Also modifies requirements.

### CODE REVIEW

**Comment by taegyunkim** [comment]
@anirudhSK Can you give me access to appveyor project? I just want to be able to re-run when it fails without weird error like 

HTTP request sent, awaiting response... 404 Not Found
2019-04-18 12:31:12 ERROR 404: Not Found.
download failed
Oracle JDK 8 is NOT installed.

**Review by anirudhSK — COMMENTED** [review]
Can you rebase this on top of the current master so that it incorporates the latest changes to appveyor.yml? I can look at it after that.

**Comment by taegyunkim** [comment]
I think I should have done `git merge master` instead of `git rebase master`...

**Comment by taegyunkim** [comment]
> Can you rebase this on top of the current master so that it incorporates the latest changes to appveyor.yml? I can look at it after that.

I think I should have merged master instead of rebasing. We're seeing some diffs because of that.

**Review by anirudhSK — APPROVED** [review]

**Pull request merged**
