### PR TITLE
Wrap hole elimination asserts with additional parentheses. 

### PR DESCRIPTION
**Pull request by taegyunkim**
It was returning `!(A == 1) && (B == 2)` instead of `!((A == 1) && (B == 2))`

### CODE REVIEW

**Review by anirudhSK — COMMENTED** [review]
Thanks for catching this. This is a bug; I am not sure how it remained dormant for so long. Can we add a test for iterative solver using the hole elimination mode to the unit tests?

**Comment by taegyunkim** [comment]
> Thanks for catching this. This is a bug; I am not sure how it remained dormant for so long. Can we add a test for iterative solver using the hole elimination mode to the unit tests?

#134 I have exactly that issue filed. We have one test case but it does not invoke the hole elimination path. I will add a test case in a separate PR.

**Comment by XiangyuG** [comment]
> > Thanks for catching this. This is a bug; I am not sure how it remained dormant for so long. Can we add a test for iterative solver using the hole elimination mode to the unit tests?
> 
> #134 I have exactly that issue filed. We have one test case but it does not invoke the hole elimination path. I will add a test case in a separate PR.

Maybe we can think up an example which will not only compile successfully with hole_elimination_mode but also take more than one iteration step. I am trying to manually design one such program.

**Comment by taegyunkim** [comment]
@XiangyuG Cool, then let's merge this first and either of us can follow up with a real example.

**Review by anirudhSK — APPROVED** [review]

**Pull request merged**
